language: node_js
node_js:
- 4
- 5
- 6

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change

deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: TODO
  on:
    tags: true
    repo: trailsjs/trailpack-bookshelf
    node: 6
